runtime: python310  # Specify the Python runtime version

entrypoint: gunicorn -b :$PORT app:app  

# Optional configurations
instance_class: F2  
automatic_scaling: 
  min_instances: 1
  max_instances: 5

# Optional: handlers for static files and templates
handlers:
  - url: /static
    static_dir: static/

  - url: /.*
    script: auto  
